'use client'

import { useLanguage } from '../../../components/LanguageProvider'

interface BikeROICardProps { collapseRoi: boolean; setCollapseRoi: (val: boolean) => void; bikePriceInput: string; handleBikePriceChange: (val: string) => void; handleBikePriceBlur: () => void; estimatedSavings: string; roiPercentageStr: string; roiPercentageNum: number; isFullyPaidBack: boolean; paybackText: string }

export function BikeROICard(props: BikeROICardProps) {
  const { t } = useLanguage()
  const { collapseRoi, setCollapseRoi, bikePriceInput, handleBikePriceChange, handleBikePriceBlur, estimatedSavings, roiPercentageStr, roiPercentageNum, paybackText } = props
  return <section className="space-y-4 rounded-2xl border border-slate-100 bg-white p-3.5 shadow-sm md:p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><button onClick={() => setCollapseRoi(!collapseRoi)} title={collapseRoi ? t.expand : t.collapse} className="flex h-6 w-6 items-center justify-center rounded-lg bg-slate-100 text-xs font-bold text-slate-600 hover:bg-slate-200">{collapseRoi ? '+' : '−'}</button><h2 className="text-base font-semibold text-slate-800 md:text-lg">🚲 {t.bikeRoi}</h2></div>{!collapseRoi && <label className="flex items-center gap-2 text-xs text-slate-400"><span className="hidden md:inline">{t.bikeCost}</span><input type="number" value={bikePriceInput} onChange={e => handleBikePriceChange(e.target.value)} onBlur={handleBikePriceBlur} className="w-20 rounded-xl border border-slate-200 px-2.5 py-1 text-center text-xs font-medium text-slate-700 focus:border-sky-500 focus:outline-none md:w-24 md:text-sm" /></label>}</div>{!collapseRoi && <div className="space-y-4 pt-1"><div className="grid grid-cols-1 gap-3 md:grid-cols-3">{[[t.savings, `£${estimatedSavings}`, 'text-slate-800'], [t.roiRate, `${roiPercentageStr}%`, 'text-emerald-600'], [t.estimatedPayback, paybackText, 'text-slate-700']].map(([label, value, color]) => <div key={label} className="rounded-xl border border-slate-100 bg-slate-50/80 p-3.5"><span className="block text-xs font-medium text-slate-400">{label}</span><span className={`mt-1 block font-bold ${color}`}>{value}</span></div>)}</div><div className="rounded-xl border border-slate-100 bg-slate-50/50 p-3"><div className="flex justify-between text-xs font-medium"><span className="text-slate-500">{t.progress}</span><span className="font-bold text-emerald-600">{roiPercentageStr}%</span></div><div className="mt-1.5 h-3 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-gradient-to-r from-sky-500 to-emerald-500" style={{ width: `${Math.min(100, Math.max(0, roiPercentageNum))}%` }} /></div></div></div>}</section>
}
