'use client'

import { useLanguage } from '../../../components/LanguageProvider'

interface BikeROICardProps { collapseRoi: boolean; setCollapseRoi: (value: boolean) => void; bikePriceInput: string; handleBikePriceChange: (value: string) => void; handleBikePriceBlur: () => void; estimatedSavings: string; roiPercentageStr: string; roiPercentageNum: number; isFullyPaidBack: boolean; paybackText: string }

export function BikeROICard(p: BikeROICardProps) {
  const { t } = useLanguage()
  const metrics = [[t.savings, `£${p.estimatedSavings}`, 'text-slate-800'], [t.roiRate, `${p.roiPercentageStr}%`, 'text-emerald-600'], [t.estimatedPayback, p.paybackText, 'text-slate-700']]
  return <section className="space-y-4 rounded-2xl border border-slate-100 bg-white p-3.5 shadow-sm md:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-2"><button onClick={() => p.setCollapseRoi(!p.collapseRoi)} title={p.collapseRoi ? t.expand : t.collapse} className="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-xs font-bold text-slate-600">{p.collapseRoi ? '+' : '-'}</button><h2 className="min-w-0 text-base font-semibold text-slate-800 md:text-lg">{t.bikeRoi}</h2></div>{!p.collapseRoi && <label className="flex w-full items-center justify-between gap-3 text-xs font-medium text-slate-500 sm:w-auto sm:justify-end">{t.bikeCost}<input type="number" min="0" value={p.bikePriceInput} onChange={event => p.handleBikePriceChange(event.target.value)} onBlur={p.handleBikePriceBlur} className="w-24 rounded-xl border border-slate-200 px-2.5 py-1.5 text-center text-sm font-semibold text-slate-700 focus:border-sky-500 focus:outline-none" /></label>}</div>{!p.collapseRoi && <><div className="grid grid-cols-1 gap-3 md:grid-cols-3">{metrics.map(([label, value, color]) => <div key={label} className="rounded-xl border border-slate-100 bg-slate-50/80 p-3.5"><span className="block text-xs font-medium text-slate-400">{label}</span><span className={`mt-1 block font-bold ${color}`}>{value}</span></div>)}</div><div className="rounded-xl border border-slate-100 bg-slate-50/50 p-3"><div className="flex justify-between text-xs font-medium"><span className="text-slate-500">{t.progress}</span><span className="font-bold text-emerald-600">{p.roiPercentageStr}%</span></div><div className="mt-1.5 h-3 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-gradient-to-r from-sky-500 to-emerald-500" style={{ width: `${Math.min(100, Math.max(0, p.roiPercentageNum))}%` }} /></div></div></>}</section>
}
