'use client'

import { useLanguage } from '../../../components/LanguageProvider'
import { dashboardCardClass, dashboardCardTitleClass, dashboardCollapseButtonClass } from '../_lib/module-ui'

interface SyncStatusProps { collapseSync: boolean; setCollapseSync: (value: boolean) => void; isConnected: boolean; stravaAuthUrl: string; handleSync: () => void; handleFullResync: () => void; isSyncing: boolean; errorMessage?: string }

export function SyncStatus(props: SyncStatusProps) {
  const { t, lang } = useLanguage()
  const retry = lang === 'zh' ? '重试同步' : 'Retry sync'
  return <section className={`${dashboardCardClass} space-y-3`}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-2"><button onClick={() => props.setCollapseSync(!props.collapseSync)} title={props.collapseSync ? t.expand : t.collapse} className={dashboardCollapseButtonClass}>{props.collapseSync ? '+' : '-'}</button><h2 className={`${dashboardCardTitleClass} whitespace-nowrap`}>{t.syncTitle}</h2></div>{!props.collapseSync && <div className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap sm:justify-end">{props.isConnected ? <span className="rounded-xl border border-green-200 bg-green-50 px-3 py-1.5 text-center text-xs font-medium text-green-700">{t.connected}</span> : <a href={props.stravaAuthUrl} className="rounded-xl bg-[#FC4C02] px-3 py-1.5 text-center text-xs font-medium text-white">{t.connectStrava}</a>}<button onClick={props.handleSync} disabled={props.isSyncing} className="rounded-xl bg-sky-600 px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50">{props.isSyncing ? t.syncing : props.errorMessage ? retry : t.syncData}</button><button onClick={props.handleFullResync} disabled={props.isSyncing} className="col-span-2 rounded-xl bg-violet-600 px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50 sm:col-auto">{props.isSyncing ? t.recalculating : t.fullResync}</button></div>}</div>{!props.collapseSync && <><p className="text-xs text-slate-500 md:text-sm">{t.syncDesc}</p>{props.errorMessage && <div className="rounded-xl border border-rose-100 bg-rose-50 p-3 text-xs text-rose-700"><p className="font-medium">{props.errorMessage}</p><button onClick={props.handleSync} disabled={props.isSyncing} className="mt-2 rounded-lg bg-white px-3 py-1.5 font-semibold text-rose-700 shadow-sm disabled:opacity-50">{retry}</button></div>}</>}</section>
}
