'use client'

import Link from 'next/link'
import { useLanguage } from '../../../components/LanguageProvider'
import { dashboardCardClass, dashboardCardTitleClass, dashboardCollapseButtonClass } from '../_lib/module-ui'

interface SyncStatusProps { collapseSync: boolean; setCollapseSync: (value: boolean) => void; isConnected: boolean; stravaAuthUrl: string; handleSync: () => void; handleFullResync: () => void; isSyncing: boolean; errorMessage?: string; demo?: boolean }

export function SyncStatus(props: SyncStatusProps) {
  const { t } = useLanguage()
  if (props.demo) return <section className={`${dashboardCardClass} space-y-3`}><div className="flex items-center gap-2"><button onClick={() => props.setCollapseSync(!props.collapseSync)} className={dashboardCollapseButtonClass}>{props.collapseSync ? '+' : '−'}</button><h2 className={dashboardCardTitleClass}>Strava sync</h2></div>{!props.collapseSync && <><p className="text-sm text-slate-500">Sample rides are shown in Demo Mode. Create an account to connect Strava and sync your own activity.</p><Link href="/login" className="inline-flex rounded-xl bg-[#FC4C02] px-3 py-2 text-xs font-medium text-white">Create an account to connect Strava</Link></>}</section>
  return <section className={`${dashboardCardClass} space-y-3`}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-2"><button onClick={() => props.setCollapseSync(!props.collapseSync)} title={props.collapseSync ? t.expand : t.collapse} className={dashboardCollapseButtonClass}>{props.collapseSync ? '+' : '-'}</button><h2 className={`${dashboardCardTitleClass} whitespace-nowrap`}>{t.syncTitle}</h2></div>{!props.collapseSync && <div className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap sm:justify-end">{props.isConnected ? <span className="rounded-xl border border-green-200 bg-green-50 px-3 py-1.5 text-center text-xs font-medium text-green-700">{t.connected}</span> : <a href={props.stravaAuthUrl} className="rounded-xl bg-[#FC4C02] px-3 py-1.5 text-center text-xs font-medium text-white">{t.connectStrava}</a>}<button onClick={props.handleSync} disabled={props.isSyncing} className="rounded-xl bg-sky-600 px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50">{props.isSyncing ? t.syncing : t.syncData}</button><button onClick={props.handleFullResync} disabled={props.isSyncing} className="col-span-2 rounded-xl bg-violet-600 px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50 sm:col-auto">{props.isSyncing ? t.recalculating : t.fullResync}</button></div>}</div>{!props.collapseSync && <p className="text-xs text-slate-500 md:text-sm">{t.syncDesc}</p>}</section>
}
