'use client'

import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts'
import { useLanguage } from '../../../components/LanguageProvider'

interface WeeklyChartProps { collapseChart: boolean; setCollapseChart: (value: boolean) => void; chartData: Array<{ shortWeek: string; distance: number; savings: number }> }

export function WeeklyChart({ collapseChart, setCollapseChart, chartData }: WeeklyChartProps) {
  const { lang } = useLanguage()
  if (chartData.length === 0) return null
  const labels = lang === 'zh' ? { title: '\u5468\u5ea6\u9a91\u884c\u91cc\u7a0b\u4e0e\u8282\u7701\u5f00\u652f\u8d8b\u52bf', subtitle: '\u6bd4\u8f83\u6bcf\u5468\u9a91\u884c\u8ddd\u79bb (km) \u4e0e\u8282\u7701\u91d1\u989d (£)', distance: '\u9a91\u884c\u91cc\u7a0b', savings: '\u8282\u7701\u5f00\u652f', expand: '\u5c55\u5f00\u6a21\u5757', collapse: '\u6536\u8d77\u6a21\u5757' } : { title: 'Weekly distance & savings trend', subtitle: 'Comparing weekly distance (km) and savings (£)', distance: 'Distance', savings: 'Savings', expand: 'Expand section', collapse: 'Collapse section' }
  return <section className="space-y-3 rounded-2xl border border-slate-100 bg-white p-3.5 shadow-sm md:p-6"><div className="flex flex-col justify-between gap-2 md:flex-row md:items-center"><div className="flex items-center gap-2"><button onClick={() => setCollapseChart(!collapseChart)} title={collapseChart ? labels.expand : labels.collapse} className="flex h-6 w-6 items-center justify-center rounded-lg bg-slate-100 text-xs font-bold text-slate-600">{collapseChart ? '+' : '-'}</button><div><h2 className="text-base font-semibold text-slate-800 md:text-lg">{labels.title}</h2>{!collapseChart && <p className="mt-0.5 text-xs text-slate-400 md:text-sm">{labels.subtitle}</p>}</div></div>{!collapseChart && <div className="flex gap-3 text-xs font-medium"><span className="text-sky-600">● {labels.distance}</span><span className="text-emerald-600">● {labels.savings}</span></div>}</div>{!collapseChart && <div className="h-64 w-full pt-1 md:h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} margin={{ top: 10, right: 0, left: -20, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" /><XAxis dataKey="shortWeek" tickLine={false} tick={{ fill: '#64748b', fontSize: 10 }} /><YAxis yAxisId="left" tickLine={false} axisLine={false} tick={{ fill: '#0284c7', fontSize: 10 }} /><YAxis yAxisId="right" orientation="right" tickLine={false} axisLine={false} tick={{ fill: '#059669', fontSize: 10 }} /><Tooltip formatter={(value: unknown, name: unknown) => [String(name) === 'distance' ? `${value ?? ''} km` : `£${value ?? ''}`, String(name) === 'distance' ? labels.distance : labels.savings]} /><Bar yAxisId="left" dataKey="distance" name="distance" fill="#0284c7" radius={[4, 4, 0, 0]} barSize={12} /><Bar yAxisId="right" dataKey="savings" name="savings" fill="#10b981" radius={[4, 4, 0, 0]} barSize={12} /></BarChart></ResponsiveContainer></div>}</section>
}
